//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C969_WGU_TallisJordan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C969_WGU_TallisJordan.Resources.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Appointment.
        /// </summary>
        internal static string AddAppoint {
            get {
                return ResourceManager.GetString("AddAppoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Appointment.
        /// </summary>
        internal static string AddApptTitle {
            get {
                return ResourceManager.GetString("AddApptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add city.
        /// </summary>
        internal static string AddCity {
            get {
                return ResourceManager.GetString("AddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add country.
        /// </summary>
        internal static string AddCountry {
            get {
                return ResourceManager.GetString("AddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string AddCustomer {
            get {
                return ResourceManager.GetString("AddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be filled out.
        /// </summary>
        internal static string AllFieldsFilled {
            get {
                return ResourceManager.GetString("AllFieldsFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Months.
        /// </summary>
        internal static string AllMonths {
            get {
                return ResourceManager.GetString("AllMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be alphanumeric.
        /// </summary>
        internal static string Alphanum {
            get {
                return ResourceManager.GetString("Alphanum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an appointment with.
        /// </summary>
        internal static string AppointmentReminder {
            get {
                return ResourceManager.GetString("AppointmentReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string AppointmentReport {
            get {
                return ResourceManager.GetString("AppointmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add appointment.
        /// </summary>
        internal static string ApptAddFail {
            get {
                return ResourceManager.GetString("ApptAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment added successfully.
        /// </summary>
        internal static string ApptAddSuccess {
            get {
                return ResourceManager.GetString("ApptAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Alert.
        /// </summary>
        internal static string ApptAlert {
            get {
                return ResourceManager.GetString("ApptAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete appointment.
        /// </summary>
        internal static string ApptDelFail {
            get {
                return ResourceManager.GetString("ApptDelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete appointment. It may be linked to other data..
        /// </summary>
        internal static string ApptDelFailLink {
            get {
                return ResourceManager.GetString("ApptDelFailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment deleted successfully.
        /// </summary>
        internal static string ApptDelSuccess {
            get {
                return ResourceManager.GetString("ApptDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred fetching appointment info.
        /// </summary>
        internal static string ApptFetchError {
            get {
                return ResourceManager.GetString("ApptFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving all appointments.
        /// </summary>
        internal static string ApptGetAllError {
            get {
                return ResourceManager.GetString("ApptGetAllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update appointment.
        /// </summary>
        internal static string ApptModFailed {
            get {
                return ResourceManager.GetString("ApptModFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment updated successfully.
        /// </summary>
        internal static string ApptModSuccess {
            get {
                return ResourceManager.GetString("ApptModSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment not found.
        /// </summary>
        internal static string ApptNotFound {
            get {
                return ResourceManager.GetString("ApptNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this appointment?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this customer?.
        /// </summary>
        internal static string AreYouSureCust {
            get {
                return ResourceManager.GetString("AreYouSureCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar View.
        /// </summary>
        internal static string CalendarButton {
            get {
                return ResourceManager.GetString("CalendarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarLabel {
            get {
                return ResourceManager.GetString("CalendarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar View.
        /// </summary>
        internal static string CalendarView {
            get {
                return ResourceManager.GetString("CalendarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTitle {
            get {
                return ResourceManager.GetString("CancelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add city.
        /// </summary>
        internal static string CityAddFail {
            get {
                return ResourceManager.GetString("CityAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City added successfully.
        /// </summary>
        internal static string CityAddSuccess {
            get {
                return ResourceManager.GetString("CityAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled, city not added.
        /// </summary>
        internal static string CityOpCancel {
            get {
                return ResourceManager.GetString("CityOpCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this appointment?.
        /// </summary>
        internal static string ConfirmDelAppt {
            get {
                return ResourceManager.GetString("ConfirmDelAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant not found.
        /// </summary>
        internal static string ConsulNotFound {
            get {
                return ResourceManager.GetString("ConsulNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string ConsultantTitle {
            get {
                return ResourceManager.GetString("ConsultantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string ConsutltantTitle {
            get {
                return ResourceManager.GetString("ConsutltantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add country.
        /// </summary>
        internal static string CountryAddFail {
            get {
                return ResourceManager.GetString("CountryAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country added successfully.
        /// </summary>
        internal static string CountryAddSuccess {
            get {
                return ResourceManager.GetString("CountryAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled, country not added.
        /// </summary>
        internal static string CountryOpCancel {
            get {
                return ResourceManager.GetString("CountryOpCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer added successfully.
        /// </summary>
        internal static string CustAddSuccess {
            get {
                return ResourceManager.GetString("CustAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer has existing appointments. Delete all appointments and the customer?.
        /// </summary>
        internal static string CustApptDel {
            get {
                return ResourceManager.GetString("CustApptDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer data is not available.
        /// </summary>
        internal static string CustDataNotAvail {
            get {
                return ResourceManager.GetString("CustDataNotAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer deleted successfully.
        /// </summary>
        internal static string CustDelSuccess {
            get {
                return ResourceManager.GetString("CustDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer already exists.
        /// </summary>
        internal static string CustExists {
            get {
                return ResourceManager.GetString("CustExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CustLabel {
            get {
                return ResourceManager.GetString("CustLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update customer.
        /// </summary>
        internal static string CustModFail {
            get {
                return ResourceManager.GetString("CustModFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer updated successfully.
        /// </summary>
        internal static string CustModSuccess {
            get {
                return ResourceManager.GetString("CustModSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found for the specified customer.
        /// </summary>
        internal static string CustNoDataFound {
            get {
                return ResourceManager.GetString("CustNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string CustomerLabel {
            get {
                return ResourceManager.GetString("CustomerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Not Found.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string CustomerReport {
            get {
                return ResourceManager.GetString("CustomerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CustomerTitle {
            get {
                return ResourceManager.GetString("CustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete customer.
        /// </summary>
        internal static string DelCust {
            get {
                return ResourceManager.GetString("DelCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer has existing appointments. Delete all appointsments and the customer?.
        /// </summary>
        internal static string DeleteCustAppt {
            get {
                return ResourceManager.GetString("DeleteCustAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this customer?.
        /// </summary>
        internal static string DeleteCustomer {
            get {
                return ResourceManager.GetString("DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescripTitle {
            get {
                return ResourceManager.GetString("DescripTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password cannot be empty.
        /// </summary>
        internal static string EmpUserPass {
            get {
                return ResourceManager.GetString("EmpUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be after start time.
        /// </summary>
        internal static string EndAfterStart {
            get {
                return ResourceManager.GetString("EndAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string EndTitle {
            get {
                return ResourceManager.GetString("EndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer name to delete.
        /// </summary>
        internal static string EnterCustNameDel {
            get {
                return ResourceManager.GetString("EnterCustNameDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter customer name to modify.
        /// </summary>
        internal static string EnterCustNameMod {
            get {
                return ResourceManager.GetString("EnterCustNameMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add customer.
        /// </summary>
        internal static string FailCustAdd {
            get {
                return ResourceManager.GetString("FailCustAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load customers.
        /// </summary>
        internal static string FailCustLoad {
            get {
                return ResourceManager.GetString("FailCustLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete appointment.
        /// </summary>
        internal static string FailDelAppt {
            get {
                return ResourceManager.GetString("FailDelAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete customer.
        /// </summary>
        internal static string FailedCustDel {
            get {
                return ResourceManager.GetString("FailedCustDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update appointment.
        /// </summary>
        internal static string FailUpdateAppt {
            get {
                return ResourceManager.GetString("FailUpdateAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields cannot be empty.
        /// </summary>
        internal static string FieldsCannotBeEmpty {
            get {
                return ResourceManager.GetString("FieldsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name cannot be empty.
        /// </summary>
        internal static string FillCustName {
            get {
                return ResourceManager.GetString("FillCustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General error.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection failed.
        /// </summary>
        internal static string GenericSQLError {
            get {
                return ResourceManager.GetString("GenericSQLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the next 15 minutes.
        /// </summary>
        internal static string InNext15Minutes {
            get {
                return ResourceManager.GetString("InNext15Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationTitle {
            get {
                return ResourceManager.GetString("LocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login attempt for user.
        /// </summary>
        internal static string LoginAttemptForUser {
            get {
                return ResourceManager.GetString("LoginAttemptForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during login validation.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and password do not match.
        /// </summary>
        internal static string LoginErrorMsg {
            get {
                return ResourceManager.GetString("LoginErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Portal.
        /// </summary>
        internal static string LoginFormTitle {
            get {
                return ResourceManager.GetString("LoginFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login below.
        /// </summary>
        internal static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successful!.
        /// </summary>
        internal static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Screen.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Appointment.
        /// </summary>
        internal static string ModApptTitle {
            get {
                return ResourceManager.GetString("ModApptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify customer.
        /// </summary>
        internal static string ModCust {
            get {
                return ResourceManager.GetString("ModCust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Customer.
        /// </summary>
        internal static string ModifyCustomerTitle {
            get {
                return ResourceManager.GetString("ModifyCustomerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointments.
        /// </summary>
        internal static string NoAppts {
            get {
                return ResourceManager.GetString("NoAppts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointments found for.
        /// </summary>
        internal static string NoApptsForUser {
            get {
                return ResourceManager.GetString("NoApptsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer found with the name provided. Please try again..
        /// </summary>
        internal static string NoCustFound {
            get {
                return ResourceManager.GetString("NoCustFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found in.
        /// </summary>
        internal static string NotFoundIn {
            get {
                return ResourceManager.GetString("NotFoundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found with the name.
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the name and try again.
        /// </summary>
        internal static string NoUserFoundFix {
            get {
                return ResourceManager.GetString("NoUserFoundFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This consultant has overlapping appointments. Please choose a different time..
        /// </summary>
        internal static string OverlappingConsAppt {
            get {
                return ResourceManager.GetString("OverlappingConsAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer has overlapping appointments. Please choose a different time..
        /// </summary>
        internal static string OverlappingCustAppt {
            get {
                return ResourceManager.GetString("OverlappingCustAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PassLabel {
            get {
                return ResourceManager.GetString("PassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be in the format XXX-XXX-XXXX.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code must be exactly 5 digits.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportLabel {
            get {
                return ResourceManager.GetString("ReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Viewer.
        /// </summary>
        internal static string ReportViewer {
            get {
                return ResourceManager.GetString("ReportViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveTitle {
            get {
                return ResourceManager.GetString("SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Conflict.
        /// </summary>
        internal static string ScheduleConflict {
            get {
                return ResourceManager.GetString("ScheduleConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        internal static string ScheduleReport {
            get {
                return ResourceManager.GetString("ScheduleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment times must be within business hours (9 AM to 5 PM EST).
        /// </summary>
        internal static string ScheduleTimes {
            get {
                return ResourceManager.GetString("ScheduleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment must be scheduled on a weekday (Monday to Friday).
        /// </summary>
        internal static string ScheduleWeekday {
            get {
                return ResourceManager.GetString("ScheduleWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an appointment to delete.
        /// </summary>
        internal static string SelectApptDel {
            get {
                return ResourceManager.GetString("SelectApptDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an appointment to modify.
        /// </summary>
        internal static string SelectApptMod {
            get {
                return ResourceManager.GetString("SelectApptMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an appointment type.
        /// </summary>
        internal static string SelectApptType {
            get {
                return ResourceManager.GetString("SelectApptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a consultant.
        /// </summary>
        internal static string SelectConsul {
            get {
                return ResourceManager.GetString("SelectConsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection required.
        /// </summary>
        internal static string SelectReq {
            get {
                return ResourceManager.GetString("SelectReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a type.
        /// </summary>
        internal static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add it?.
        /// </summary>
        internal static string ShouldAddit {
            get {
                return ResourceManager.GetString("ShouldAddit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL error.
        /// </summary>
        internal static string SQLError {
            get {
                return ResourceManager.GetString("SQLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be before end time.
        /// </summary>
        internal static string StartBeforeEnd {
            get {
                return ResourceManager.GetString("StartBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartTitle {
            get {
                return ResourceManager.GetString("StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleTitle {
            get {
                return ResourceManager.GetString("TitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeTitle {
            get {
                return ResourceManager.GetString("TypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URLTitle {
            get {
                return ResourceManager.GetString("URLTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserLabel {
            get {
                return ResourceManager.GetString("UserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be empty.
        /// </summary>
        internal static string UserNotEmpty {
            get {
                return ResourceManager.GetString("UserNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the user to view their schedule.
        /// </summary>
        internal static string UserScheduleName {
            get {
                return ResourceManager.GetString("UserScheduleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Schedule Report.
        /// </summary>
        internal static string UserScheduleReport {
            get {
                return ResourceManager.GetString("UserScheduleReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
